apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deploy
  labels:
    app: k8s-demo
  annotations:
spec:
  selector:
    matchLabels:
      app: k8s-demo
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      containers:
      - name: k8s-demo
        image: meeky/k8s:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "500m"