apiVersion: v1
kind: Service
metadata:
  name: k8s-service
  labels:
    app: k8s-demo
spec:
  type: ClusterIP
  selector:
    app: k8s-demo
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000